JSInformation="SELECT \
sSalesName \
,sCardNo \
,sMaterialNo \
,tCardTime \
,sWorkingProcedureName \
,sTopColor \
,sSaleGroupName \
,tFactStartTime \
,tFactEndTime \
,sISKanBanRush \
,sKanBanRemark \
,ID \
,nCount \
,nSaleCount \
,sWorkingProcedureName2 \
,nWorkingProcedureCount \
FROM [dbo].[pbCommonDataJSKanBan]"